### ISSUE TITLE
ActiveRecord::Encryption::Errors::Decryption error on login after upgrade to Rails 7.1 defaults

### ISSUE THREAD

**Issue by collimarco** [devise-two-factor/devise-two-factor#258]
After **upgrading Rails defaults** from 7.0 to 7.1, I get this error on login when 2FA is enabled:

```
ActiveRecord::Encryption::Errors::Decryption (ActiveRecord::Encryption::Errors::Decryption):
  
activerecord (7.1.1) lib/active_record/encryption/encryptor.rb:58:in `rescue in decrypt'
activerecord (7.1.1) lib/active_record/encryption/encryptor.rb:52:in `decrypt'
activerecord (7.1.1) lib/active_record/encryption/encrypted_attribute_type.rb:86:in `block in decrypt'
activerecord (7.1.1) lib/active_record/encryption/scheme.rb:69:in `with_context'
activerecord (7.1.1) lib/active_record/encryption
```

```
[500] POST /users/sign_in (Devise::SessionsController#create)
```

Do you have any idea how to fix this?

**Comment by collimarco** [comment]
Now I also tried to add this line:

```
# config/application.rb

config.active_record.encryption.hash_digest_class = OpenSSL::Digest::SHA256
```

But we get the same error....
Any idea?

**Comment by collimarco** [comment]
Also note that all the tests are passing:

```
it_behaves_like "two_factor_authenticatable"
it_behaves_like "two_factor_backupable"
```

But actually it doesn't work in production, you get that exception

**Comment by collimarco** [comment]
Solved.

Here's the solution for anyone having the same issue: https://github.com/rails/rails/issues/48204#issuecomment-1760022815
